name: Import FunkoDB to Supabase

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  import:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Run FunkoDB import script
        run: node scripts/import-funkodb-to-supabase.js funkodb.json 